export const FETCH_CORONA_STATISTICS = 'FETCH_CORONA_STATISTICS';
export const SHOW_COUNTRY_STATISTICS = 'SHOW_COUNTRY_STATISTICS';
export const FETCH_MARKERS = 'FETCH_MARKERS';
export const MAP_STYLE= 'MAP_STYLE';
export const SET_ACTION = 'SET_ACTION';
export const MAP_STYLE_ACTION = 'MAP_STYLE_ACTION';
export const MAP_FLY_ACTION = 'MAP_FLY_ACTION';

export const BASE_URL = `http://127.0.0.1:9000`;
export const MAPBOX_ACCESS_TOKEN = `pk.eyJ1IjoiYWxwb25zYSIsImEiOiJja2dtanh4dGwwN2FoMnRwcDNuc2t1ZXM3In0.DU7rUFompuY2SxztMNu9Hw`;